name: Docker image

on:
  push:
    branches:
      - 'master'

jobs:
  docker-alpine:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: klausi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push alpine image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:
            - klausi/mastodon-twitter-sync:latest,klausi/mastodon-twitter-sync:alpine

      -
        name: Build and push debian image
        uses: docker/build-push-action@v2
        with:
          file: ./debian.Dockerfile
          push: true
          tags: klausi/mastodon-twitter-sync:debian
